definitions:
  services:
    docker:
      memory: 4096
  caches:
    gradlewrapper: ~/.gradle/wrapper
    sonar: ~/.sonar/
  steps:
    - step: &quality-check
        name: Quality Check 
        caches: 
          - node
        script:
          - ls -al node_modules/ || true
          - env
        artifacts:
          - '**/*.js'

image: node
pipelines:
  custom:
    quality:
      - variables:
        - name: Username
        - name: Region
          default: ap-southeast-2  # optionally provide a default value
      - step: *quality-check
  
  default1:
    - step:
        name: 'Build and Test'
        caches:
          - node
          - gradlewrapper
        script:
          - echo "Your build and test goes here..."
          - echo Hello > newfile.txt
        artifacts:
          - 'newfile.txt'

    - step:
        name: 'Build and Test2'
        caches:
          - node
          - gradlewrapper
        script:
          - echo "Your build and test goes here..."
          - cat newfile.txt
          - echo Bye > newfile.txt
          - echo $TEST_VAR
        artifacts:
          - 'newfile.txt'

    - parallel:
      - step:
          name: 'P1'
          script:
            - env
            - echo "P1"
      - step:
          name: 'P2'
          script:
            - env
            - echo "P2"
      - step:
          name: 'P3'
          script:
            - env
            - echo "P3"